---
title: "Clustering Analysis"
author: "Shrikanth"
date: "October 18, 2018"
output:   rmarkdown::github_document
---

```{r}
knitr::opts_chunk$set(echo = FALSE)
library(png)
library(grid)
library(quantreg)
library(highfrequency)
library(TTR)
library(lubridate)
library(timeSeries)
library(dplyr)
library(ggplot2)
library("gridExtra")
library("cowplot")
theme_set(theme_grey())
library(reshape2)
library(scales)
source("src/TSA_source.R")
source("TSA_Data_Source.R")
source("src/plotting_functions.R")
```


# Extraction

```{r, echo = TRUE, warning=FALSE}

C_data <- read.csv(file = 'Raw Sensor Data/Climo_co_corr_IISc_1_10.csv', header = TRUE, sep = ";")
cTime <-  as.POSIXct(C_data$Time)#(,"%Y-%m-%d %H:%M:%S", tz = "")
ws_c <- as.numeric(mean(diff(cTime)))*60 # sampling frequecy (seconds)
xts.c <- xts(x = C_data$Value, order.by = cTime)


daily_threshold <- floor(1170) # Expected number of samples per day
frequency_tolerance.c = 10
frequency_tolerance.w = 10
fault_window = "hours" # to identify faults in the data
std_tolerance = 0.01
dir.create("plots",showWarnings=FALSE,recursive=TRUE)

```



## Main dataframe

```{r overall_dataset, echo=TRUE, warning=FALSE, fig.height=5}

avg_time = 1

# df.new <- get_ts_master_dataFrame('Raw Sensor Data/Wind_direction_corr_IISc_1_20.csv', 
#                               'Raw Sensor Data/Climo_co_corr_IISc_1_10.csv', 
#                               'Raw Sensor Data/Wind_speed_corr_IISc_1_20.csv', 
#                               avg_time)
df.new <- getMasterdf_September(avg_time)
refTime <- as.POSIXct(df.new$time)
df.seasonal <- getSeasonality(df.new, avg_time)
# Plot overall time series
plot.TS_Overall(xts.c, type = "CO Concentrations",folder = "plots")
# Plot Dataframe with fautly rows in red
plot.DF_faults(df.new,df.specs = "Carbon Monoxide", avg_time, folder = "plots")


```

# Clustering

We can now perform the numerous tests by clustering the dataset into three major clusters.

```{r}
df.new$dos <- day(df.new$time)
```
## Clustering based on dates 
```{r}
cluster1 <- c(2,3,4)
cluster2 <- c(5,6,7)
cluster3 <- c(8,9,10)

for(i in 1:3){
  idx <- df.new$dos == cluster1[i]
  df.new$cluster[idx] = "cluster1"
  idx <- df.new$dos == cluster2[i]
  df.new$cluster[idx] = "cluster2"
  idx <- df.new$dos == cluster3[i]
  df.new$cluster[idx] = "cluster3"
}
idx <- is.na(df.new$cluster)
df.new <- df.new[!is.na(df.new$cluster), ]
df.new$time = as.POSIXct(df.new$time)
plt_all <- ggplot(df.new, aes(x= time, y = conc, color = cluster)) +theme_gray(base_size = 24)+ 
  geom_line(size = 1.5) + theme(legend.position = "none")+
  # ylab(bquote('Conc. ('*mu~'g'~m^-3*')'))+xlab("Time (Days)")#+labs(color = "Legend")
  ylab('Conc. (ppm)')+xlab("Time (Days)")#+labs(color = "Legend")

folder = "plots"
df.specs = "CO_Concentrations_clust"
formats = c("PDF", "PNG")
plot.folder <- paste(folder,"/TS_overall/",sep="")
dir.create(plot.folder,showWarnings=FALSE,recursive=TRUE)

# record plot
#	print(data)
for(format in formats){
  plot.filename <- paste(plot.folder,"dfName=",df.specs,".",format,sep="")
  if(!is.na(format)){
    if(format=="PDF")
      pdf(file=plot.filename,bg="white")
    else if(format=="PNG")
      png(filename=plot.filename,width=800,height=800,units="px",pointsize=20,bg="white")
  }
  
  print(plt_all) #suppressMessages(print(plt))
  
  if(!is.na(format))
    dev.off()
}  
print(plt_all)
```

## Seasonality in each cluster
```{r}
df.sea <- data.frame(cluster1 = array(0, 24/avg_time), 
                     cluster2  = array(0, 24/avg_time), 
                     cluster3 = array(0, 24/avg_time))

tmp <- getSeasonality(df.new[df.new$cluster=="cluster1",], avg_time)
df.sea$cluster1 <- tmp$conc
tmp <- getSeasonality(df.new[df.new$cluster=="cluster2",], avg_time)
df.sea$cluster2 <- tmp$conc
tmp <- getSeasonality(df.new[df.new$cluster=="cluster3",], avg_time)
df.sea$cluster3 <- tmp$conc
df.sea$time <- as.POSIXct(tmp$x)

df.sea.m <- melt(df.sea, id.vars = "time")

plt_sea <- ggplot(df.sea.m, aes(x = time, y = value, color = variable))+geom_line(size = 2)+theme_gray(base_size = 24)+
  xlab("Time (Hour of day)")+ylab('Conc. (ppm)')+ scale_x_datetime(date_labels = "%H") + labs(color = "")+
  theme(legend.position=c(.38,.8), 
        legend.box = "horizontal",
        legend.background = element_rect(fill=alpha(colour = "white", alpha = 0.1)))+
  guides(color=guide_legend(direction = "horizontal"))

df.specs = "CO_seasonal_clust"
formats = c("PDF", "PNG")
plot.folder <- paste(folder,"/CO_seasonal_clust/",sep="")
dir.create(plot.folder,showWarnings=FALSE,recursive=TRUE)

# record plot
#	print(data)
for(format in formats){
  plot.filename <- paste(plot.folder,"dfName=",df.specs,".",format,sep="")
  if(!is.na(format)){
    if(format=="PDF")
      pdf(file=plot.filename,bg="white")
    else if(format=="PNG")
      png(filename=plot.filename,width=800,height=800,units="px",pointsize=20,bg="white")
  }
  
  print(plt_sea) #suppressMessages(print(plt))
  
  if(!is.na(format))
    dev.off()
}  
print(plt_sea)

final <- plot_grid(plt_all, plt_sea, nrow = 2,rel_heights = c(0.47,0.53))

df.specs = "final_CO_seasonal_clust"
formats = c("PDF", "PNG")
plot.folder <- paste(folder,"/final_plots/",sep="")
dir.create(plot.folder,showWarnings=FALSE,recursive=TRUE)

# record plot
#	print(data)
for(format in formats){
  plot.filename <- paste(plot.folder,df.specs,".",format,sep="")
  if(!is.na(format)){
    if(format=="PDF")
      pdf(file=plot.filename,bg="white")
    else if(format=="PNG")
      png(filename=plot.filename,width=800,height=800,units="px",pointsize=20,bg="white")
  }
  
  print(final) #suppressMessages(print(plt))
  
  if(!is.na(format))
    dev.off()
}  

print(final)




```


## Effect of wind speed on de-seasoned data

```{r scat_ws_conc, echo = TRUE, warning= FALSE, fig.height= 5}
folder = "plots"
df.specs = "Scat_onset_ws_deseasoned_clust"
plt_1 <- plot.Scat_ws_deseasoned(df.new, df.seasonal, df.specs, avg_time, clustering = TRUE)

```

## Effect of temperature on de-seasoned data

```{r scat_t_conc, echo = TRUE, warning= FALSE, fig.height= 5}
df.specs = "Scat_t_deseasoned_clust"
plt_2 <- plot.Scat_t_deseasoned(df.new, df.seasonal, df.specs, avg_time, clustering = TRUE)
 
plt_1 <- plt_1 + ylab("de-conc.")+
  theme_gray(base_size = 21) + 
  theme(legend.position=c(.9,.75), 
        legend.box = "vertical",
        legend.background = element_rect(fill=alpha(colour = "white", alpha = 0.1)))+
  guides(color=guide_legend(direction = "vertical"))
        # legend.text=element_text(size=18))

plt_2 <- plt_2 + 
  ylab("de-conc.")+
  theme_gray(base_size = 21)+
  theme(legend.position="bottom", 
        legend.box = "horizontal",
        legend.background = element_rect(fill=alpha(colour = "white", alpha = 0.1)))+
  guides(color=guide_legend(direction = "horizontal"))
        # legend.text=element_text(size=18))

final <- plot_grid(plt_1, plt_2, nrow = 2,rel_heights = c(0.5,0.5))


df.specs = "final_CO_corr_clust"
formats = c("PDF", "PNG")
plot.folder <- paste(folder,"/final_plots/",sep="")
dir.create(plot.folder,showWarnings=FALSE,recursive=TRUE)

# record plot
#	print(data)
for(format in formats){
  plot.filename <- paste(plot.folder,df.specs,".",format,sep="")
  if(!is.na(format)){
    if(format=="PDF")
      pdf(file=plot.filename,bg="white")
    else if(format=="PNG")
      png(filename=plot.filename,width=800,height=800,units="px",pointsize=20,bg="white")
  }
  
  print(final) #suppressMessages(print(plt))
  
  if(!is.na(format))
    dev.off()
}  

print(final)



```


## Histogram for temperature

```{r}
t.plt <- ggplot(df.new, aes(x = temp)) + facet_wrap(.~cluster)
plt <- t.plt + geom_histogram(bins = 10, fill = "gray") + theme_gray(base_size = 24) + xlab(expression(paste("Temperature")))
  # xlab(bquote('Temperature ('*^\circ~'C'~*')'))
# ylab(bquote('Conc. ('*mu~'g'~m^-3*')'))

df.specs = "clust_temp_hist"
formats = c("PDF", "PNG")
plot.folder <- paste(folder,"/",df.specs,"/",sep="")
dir.create(plot.folder,showWarnings=FALSE,recursive=TRUE)

# record plot
#	print(data)
for(format in formats){
  plot.filename <- paste(plot.folder,"dfName=",df.specs,".",format,sep="")
  if(!is.na(format)){
    if(format=="PDF")
      pdf(file=plot.filename,bg="white")
    else if(format=="PNG")
      png(filename=plot.filename,width=800,height=800,units="px",pointsize=20,bg="white")
  }
  
  print(plt) #suppressMessages(print(plt))
  
  if(!is.na(format))
    dev.off()
}  
print(plt)
plt_1 <- plt+theme(axis.text.x = element_text(angle=90))#, legend.position = "bottom")
```



## Histogram for Wind speed

```{r}
t.plt <- ggplot(df.new, aes(x = wspeed)) + facet_wrap(.~cluster)
plt <- t.plt + 
  geom_histogram(bins = 10, fill = "gray") + 
  theme_gray(base_size = 24) + 
  xlab(expression(paste("Wind Speed")))+
  theme(axis.text.x = element_text(angle=90))#, legend.position = "bottom")


df.specs = "clust_ws_hist"
formats = c("PDF", "PNG")
plot.folder <- paste(folder,"/",df.specs,"/",sep="")
dir.create(plot.folder,showWarnings=FALSE,recursive=TRUE)

# record plot
#	print(data)
for(format in formats){
  plot.filename <- paste(plot.folder,"dfName=",df.specs,".",format,sep="")
  if(!is.na(format)){
    if(format=="PDF")
      pdf(file=plot.filename,bg="white")
    else if(format=="PNG")
      png(filename=plot.filename,width=800,height=800,units="px",pointsize=20,bg="white")
  }
  
  print(plt) #suppressMessages(print(plt))
  
  if(!is.na(format))
    dev.off()
}  
print(plt)
plt_2 <- plt

final <- plot_grid(plt_2, plt_1, nrow = 2)
df.specs = "final_CO_hist_clust"
formats = c("PDF", "PNG")
plot.folder <- paste(folder,"/final_plots/",sep="")
dir.create(plot.folder,showWarnings=FALSE,recursive=TRUE)

# record plot
#	print(data)
for(format in formats){
  plot.filename <- paste(plot.folder,df.specs,".",format,sep="")
  if(!is.na(format)){
    if(format=="PDF")
      pdf(file=plot.filename,bg="white")
    else if(format=="PNG")
      png(filename=plot.filename,width=800,height=800,units="px",pointsize=20,bg="white")
  }
  
  print(final) #suppressMessages(print(plt))
  
  if(!is.na(format))
    dev.off()
}  

print(final)




```
